// Package executor runs and stops workloads as containers via Docker + NVIDIA Container Toolkit.
// For SSH workloads, it installs openssh-server inside the container and returns the endpoint + password.
package executor

import "context"

type LaunchSpec struct {
	WorkloadID     string
	Image          string
	GPUUUIDs       []string
	IdleTimeoutSec int
	Env            map[string]string
	ExposeSSH      bool
	ExposeJupyter  bool
	SSHPassword    string // pre-generated by control plane, also in Env["SSH_PASSWORD"]
	// OnStage, if set, is called with coarse deployment stages during Launch
	// (pulling_image, building_env, starting_container, configuring) so the control
	// plane can show real progress. Optional; nil-safe.
	OnStage func(stage string)
}

// stage is a nil-safe helper to report a deployment stage.
func (s LaunchSpec) stage(name string) {
	if s.OnStage != nil {
		s.OnStage(name)
	}
}

type Status struct {
	WorkloadID      string
	State           string // pending|running|stopping|stopped|failed
	SSHEndpoint     string
	SSHPassword     string
	JupyterEndpoint string
	Message         string
	Logs            string
}

type Executor interface {
	Launch(ctx context.Context, spec LaunchSpec) (Status, error)
	Stop(ctx context.Context, workloadID string) error
	Status(ctx context.Context, workloadID string) (Status, error)
	Logs(ctx context.Context, workloadID string, tail int) (string, error)
	// List enumerates every NodeHive-managed workload present on this host with its
	// live state (running containers include recovered SSH/Jupyter endpoints).
	// Used for reconciliation after the agent or control plane reconnects.
	List(ctx context.Context) ([]Status, error)
}

// Options configure the Docker executor.
type Options struct {
	// GPUPassthrough adds `--gpus` to docker run. Disable on hosts without
	// the NVIDIA Container Toolkit (e.g. a dev laptop) so launches still work.
	GPUPassthrough bool
	// AdvertiseHost is the host used in returned SSH/Jupyter endpoints.
	// Empty falls back to the machine hostname. Use "localhost" for local dev.
	AdvertiseHost string
}
